-- ==========================================
-- 0. CLEANUP (For fresh start)
-- ==========================================
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.tenant_locations CASCADE;
DROP TABLE IF EXISTS public.tenants CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ==========================================
-- 1. PROFILES (Extends Auth)
-- ==========================================
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  role text default 'tenant' check (role in ('tenant', 'staff', 'admin')),
  created_at timestamptz default now()
);
alter table public.profiles enable row level security;
create policy "Public read profiles" on profiles for select using (true);
create policy "Self update profiles" on profiles for update using (auth.uid() = id);

-- ==========================================
-- 2. LOCATIONS
-- ==========================================
create table public.locations (
  id bigint generated by default as identity primary key,
  name text not null, 
  type text not null check (type in ('daily', 'monthly')),
  rate_khemah numeric default 0,
  rate_cbs numeric default 0,
  rate_monthly numeric default 0,
  image_url text,
  created_at timestamptz default now()
);
alter table public.locations enable row level security;
create policy "Public read locations" on locations for select using (true);

-- ==========================================
-- 3. TENANTS (Business Profiles)
-- ==========================================
create table public.tenants (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id), 
  full_name text not null,
  business_name text,
  phone_number text,
  ic_number text,
  email text, 
  status text default 'active',
  created_at timestamptz default now()
);
alter table public.tenants enable row level security;
create policy "Public read tenants" on tenants for select using (true);
create policy "Self update business" on tenants for update using (profile_id = auth.uid());
create policy "Admin update business" on tenants for update using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- ==========================================
-- 4. TENANT LOCATIONS (Link Tenants -> Locations)
-- ==========================================
create table public.tenant_locations (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  location_id bigint references public.locations(id) on delete cascade,
  stall_number text,
  rate_type text check (rate_type in ('khemah', 'cbs', 'monthly')),
  status text default 'active',
  created_at timestamptz default now()
);
alter table public.tenant_locations enable row level security;
create policy "Public read tenant_locations" on tenant_locations for select using (true);

-- ==========================================
-- 5. TRANSACTIONS
-- ==========================================
create table public.transactions (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id),
  amount numeric not null,
  type text not null, -- 'income', 'expense'
  category text,
  status text default 'pending',
  date date default CURRENT_DATE,
  description text,
  created_at timestamptz default now()
);
alter table public.transactions enable row level security;
create policy "Public read transactions" on transactions for select using (true);
create policy "Auth create transactions" on transactions for insert with check (auth.role() = 'authenticated');

-- ==========================================
-- 6. AUTOMATION & TRIGGERS
-- ==========================================
create or replace function public.handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'tenant');
  
  update public.tenants 
  set profile_id = new.id 
  where email = new.email;
  
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.set_user_role(target_email text, new_role text)
returns void language plpgsql security definer as $$
begin
  update public.profiles set role = new_role where email = target_email;
end;
$$;

-- ==========================================
-- 7. SEED DATA
-- ==========================================

-- Locations
INSERT INTO public.locations (name, type, rate_khemah, rate_cbs, rate_monthly, image_url) VALUES
('Pasar Malam Seksyen 7', 'daily', 45, 35, 0, '/map-location.png'),
('Uptown Rimbayu', 'monthly', 0, 0, 650, '/uptown-map.jpg'),
('Pasar Tani Stadium', 'daily', 40, 30, 0, '/placeholder.jpg');

-- Tenants
INSERT INTO public.tenants (full_name, business_name, phone_number, email, status, ic_number) VALUES
('Ahmad Ismail', 'Nasi Lemak Royale', '0123456789', 'ahmad@permit.com', 'active', '800101-10-1234'),
('Siti Aminah', 'Siti Hijab Collection', '0198765432', 'siti@permit.com', 'active', '850505-10-5678'),
('Mohd Faizal', 'Faizal Gadget', '0172233445', 'faizal@permit.com', 'active', '901212-10-9090');

-- Tenant Locations (Linking them up)
INSERT INTO public.tenant_locations (tenant_id, location_id, stall_number, rate_type) VALUES
(1, 1, 'A-12', 'khemah'), -- Ahmad @ Pasar Malam (Daily Rate: 45)
(2, 2, 'UP-05', 'monthly'), -- Siti @ Uptown (Monthly Rate: 650)
(3, 3, 'PTS-88', 'cbs'); -- Faizal @ Stadium (CBS Rate: 30)

-- Transactions
INSERT INTO public.transactions (tenant_id, amount, type, category, status, date, description) VALUES
(1, 45.00, 'income', 'Sewa Harian', 'approved', CURRENT_DATE, 'Sewa Tapak A-12'),
(2, 650.00, 'income', 'Sewa Bulanan', 'approved', CURRENT_DATE - 1, 'Sewa Uptown Bulan Mac'),
(3, 30.00, 'income', 'Sewa CBS', 'pending', CURRENT_DATE, 'Sewa Tapak PTS-88'),
(NULL, 120.00, 'expense', 'Penyelenggaraan', 'approved', CURRENT_DATE - 2, 'Baiki Paip Pecah');