-- Create a junction table to support Many-to-Many Tenant-Organizer relationships
CREATE TABLE IF NOT EXISTS tenant_organizers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  organizer_id UUID NOT NULL REFERENCES organizers(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'active', 'rejected'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Ensure unique pair
  UNIQUE(tenant_id, organizer_id)
);

-- RLS Policies
ALTER TABLE tenant_organizers ENABLE ROW LEVEL SECURITY;

-- Tenants can insert (request to join)
CREATE POLICY "Tenants can insert own requests" ON tenant_organizers
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM tenants 
      WHERE tenants.id = tenant_organizers.tenant_id 
      AND tenants.profile_id = auth.uid()
    )
  );

-- Tenants can view their own requests
CREATE POLICY "Tenants can view own requests" ON tenant_organizers
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM tenants 
      WHERE tenants.id = tenant_organizers.tenant_id 
      AND tenants.profile_id = auth.uid()
    )
  );

-- Organizers can view requests for themselves
CREATE POLICY "Organizers can view requests for themselves" ON tenant_organizers
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM organizers 
      WHERE organizers.id = tenant_organizers.organizer_id 
      AND organizers.profile_id = auth.uid()
    )
  );

-- Organizers can update status
CREATE POLICY "Organizers can update status" ON tenant_organizers
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM organizers 
      WHERE organizers.id = tenant_organizers.organizer_id 
      AND organizers.profile_id = auth.uid()
    )
  );

-- Add RPC function to link organizer (for easier atomic operation)
CREATE OR REPLACE FUNCTION link_tenant_to_organizer(
  p_tenant_id BIGINT,
  p_organizer_code TEXT
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_organizer_id UUID;
  v_exists BOOLEAN;
  v_result JSONB;
BEGIN
  -- 1. Find Organizer by Code
  SELECT id INTO v_organizer_id
  FROM organizers
  WHERE organizer_code = p_organizer_code;

  IF v_organizer_id IS NULL THEN
    RAISE EXCEPTION 'Kod Penganjur tidak sah';
  END IF;

  -- 2. Check if already linked
  SELECT EXISTS(
    SELECT 1 FROM tenant_organizers 
    WHERE tenant_id = p_tenant_id AND organizer_id = v_organizer_id
  ) INTO v_exists;

  IF v_exists THEN
    -- Already exists, check status? Or just return success?
    -- Maybe update to pending if it was rejected?
    UPDATE tenant_organizers 
    SET status = 'pending', updated_at = now()
    WHERE tenant_id = p_tenant_id AND organizer_id = v_organizer_id;
    
    RETURN jsonb_build_object('status', 'updated', 'organizer_id', v_organizer_id);
  ELSE
    -- Insert new link
    INSERT INTO tenant_organizers (tenant_id, organizer_id, status)
    VALUES (p_tenant_id, v_organizer_id, 'pending');
    
    RETURN jsonb_build_object('status', 'inserted', 'organizer_id', v_organizer_id);
  END IF;
END;
$$;
