-- 1. Add status columns to tables if they don't exist
-- Locations
ALTER TABLE public.locations 
ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- Tenants (Ensure it exists, usually does, but for approval workflow)
ALTER TABLE public.tenants 
ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- Organizers (Already has status, but ensure default)
ALTER TABLE public.organizers 
ALTER COLUMN status SET DEFAULT 'active';

-- Transactions (Already has status usually, ensure check constraint allows 'pending')
-- Verify constraint? Just ensuring column exists for now.

-- 2. Create Action Logs Table
CREATE TABLE IF NOT EXISTS public.action_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id),
    action text not null, -- 'CREATE', 'UPDATE', 'DELETE', 'APPROVE'
    resource text not null, -- 'location', 'tenant', 'transaction', 'organizer'
    resource_id text, -- ID of the item
    details jsonb, -- Snapshot of data or details
    created_at timestamptz default now()
);

-- RLS for Logs
ALTER TABLE public.action_logs ENABLE ROW LEVEL SECURITY;

-- Admins can view ALL logs
CREATE POLICY "Admins view all logs" ON public.action_logs
    FOR SELECT USING (
        exists (select 1 from profiles where id = auth.uid() and role IN ('admin', 'superadmin'))
    );

-- Staff can view THEIR OWN logs
CREATE POLICY "Staff view own logs" ON public.action_logs
    FOR SELECT USING (
        user_id = auth.uid()
    );

-- All authenticated users can INSERT logs (System/App logic links this)
CREATE POLICY "Users can create logs" ON public.action_logs
    FOR INSERT WITH CHECK (
        auth.role() = 'authenticated'
    );

-- Admins can DELETE logs
CREATE POLICY "Admins delete logs" ON public.action_logs
    FOR DELETE USING (
        exists (select 1 from profiles where id = auth.uid() and role IN ('admin', 'superadmin'))
    );
